options:
  image:
    type: string
    default: mcr.microsoft.com/mssql/server:2019-latest
    description: The container image to use.
  accept-eula:
    type: boolean
    default: False
    description: Confirms acceptance of the End-User Licensing Agreement.
  product-id:
    type: string
    default: Developer
    description: |
      The SQL Server edition or product key. Valid options are:
        * Evaluation
        * Developer
        * Express
        * Web
        * Standard
        * Enterprise
        * A product key
      If specifying a product key, it must be in the form of
      #####-#####-#####-#####-#####, where '#' is a number or a letter.
